name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    # get code
    - uses: actions/checkout@v1

    # setup environment
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    # install deps
    - name: Install dependencies
      run: npm ci

    # test (prevents deployment for broken builds)
    - name: Test
      run: node node_modules/@angular/cli/bin/ng test --browsers=ChromeHeadless --watch=false

    # deploy
    - name: Deploy
      run: node node_modules/@angular/cli/bin/ng deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

