name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    # get code
    - uses: actions/checkout@v1

    # setup environment
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8

    # install deps
    - name: Install dependencies
      run: npm ci

    # lint
    - name: Deploy
      run: name: Test
      env: # Or as an environment variable
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    # get code
    - uses: actions/checkout@v1

    # setup environment
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8

    # install deps
    - name: Install dependencies
      run: npm ci

    # test (prevents deployment for broken builds)
    - name: Test
      run: node node_modules/@angular/cli/bin/ng test --browsers=ChromeHeadless --watch=false

    # deploy
    - name: Deploy
      run: ng deploy

