name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    # get code
    - uses: actions/checkout@v1

    # setup environment
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    # install deps
    - name: Install dependencies
      run: npm ci

    # lint
    - name: Lint
      run: node_modules/.bin/ng lint abmorrisart

    # test
    - name: Test
      run: node node_modules/@angular/cli/bin/ng test --browsers=ChromeHeadless --watch=false --code-coverage --source-map=true
